# Generated by Django 5.2.17 on 2026-08-08 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('role', models.CharField(blank=True, default='', max_length=150)),
                ('location', models.CharField(blank=True, default='', max_length=150)),
                ('package', models.CharField(blank=True, default='', help_text="CTC / stipend (free text, e.g. '6-8 LPA')", max_length=100)),
                ('drive_link', models.URLField(blank=True, default='', help_text='Link where students apply')),
                ('description', models.TextField(blank=True, default='')),
                ('eligibility', models.TextField(blank=True, default='', help_text='Eligibility criteria shown to students')),
                ('eligible_roll_numbers', models.TextField(blank=True, default='', help_text="Optional: comma/newline-separated roll numbers (paste from an Excel sheet). Students in the list get an 'Eligible for you' tag.")),
                ('last_date_to_apply', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_drives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'drives',
                'ordering': ['-created_at'],
            },
        ),
    ]
