# Generated by Django 5.2.17 on 2026-08-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0002_aiusagelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiusagelog',
            name='action',
            field=models.CharField(choices=[('AI_EXTRACT', 'AI Extract'), ('AI_CHAT', 'AI Chat'), ('AI_ASK', 'AI Ask'), ('AI_RESUME', 'AI Resume Review')], max_length=20),
        ),
    ]
