# Generated by Django 5.2.17 on 2026-08-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0003_alter_aiusagelog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='last_date_to_apply',
            field=models.DateField(blank=True, null=True),
        ),
    ]
