# Generated by Django 5.2.17 on 2026-08-09 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0004_alter_drive_last_date_to_apply'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('provider_type', models.CharField(choices=[('OPENAI_COMPATIBLE', 'OpenAI Compatible'), ('GEMINI', 'Google Gemini'), ('NVIDIA', 'NVIDIA'), ('GROQ', 'Groq'), ('CEREBRAS', 'Cerebras')], default='OPENAI_COMPATIBLE', max_length=20)),
                ('model', models.CharField(max_length=120)),
                ('base_url', models.URLField(blank=True, default='', max_length=300)),
                ('encrypted_api_key', models.TextField(blank=True, default='')),
                ('priority', models.PositiveIntegerField(default=100, help_text='Lower = tried first')),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('timeout_seconds', models.PositiveIntegerField(default=60)),
                ('max_retries', models.PositiveIntegerField(default=2)),
                ('purpose', models.CharField(choices=[('GENERAL', 'General / All tasks'), ('DRIVE_EXTRACTION', 'Drive Extraction'), ('CHAT', 'Student Chat'), ('RESUME', 'Resume Analysis'), ('WEB', 'Web Research')], default='GENERAL', max_length=20)),
                ('health', models.CharField(choices=[('HEALTHY', 'Healthy'), ('DEGRADED', 'Degraded'), ('RATE_LIMITED', 'Rate Limited'), ('UNAVAILABLE', 'Unavailable'), ('DISABLED', 'Disabled'), ('UNKNOWN', 'Unknown')], db_index=True, default='UNKNOWN', max_length=20)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_type', models.CharField(blank=True, default='', max_length=40)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('total_requests', models.PositiveIntegerField(default=0)),
                ('total_errors', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_ai', models.BooleanField(default=True)),
                ('enable_fallback', models.BooleanField(default=True)),
                ('enable_caching', models.BooleanField(default=True)),
                ('enable_web_research', models.BooleanField(default=True)),
                ('default_timeout_seconds', models.PositiveIntegerField(default=60)),
                ('default_max_retries', models.PositiveIntegerField(default=2)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'AI settings',
            },
        ),
        migrations.CreateModel(
            name='AIProviderHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('HEALTHY', 'Healthy'), ('DEGRADED', 'Degraded'), ('RATE_LIMITED', 'Rate Limited'), ('UNAVAILABLE', 'Unavailable'), ('DISABLED', 'Disabled'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_type', models.CharField(blank=True, default='', max_length=40)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_row', to='placements.aiprovider')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIProviderKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_api_key', models.TextField(blank=True, default='')),
                ('note', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='placements.aiprovider')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(blank=True, default='', max_length=30)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], db_index=True, max_length=10)),
                ('primary_provider', models.CharField(blank=True, default='', max_length=80)),
                ('provider_used', models.CharField(blank=True, default='', max_length=80)),
                ('fallback_used', models.BooleanField(db_index=True, default=False)),
                ('error_type', models.CharField(blank=True, default='', max_length=40)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='placements.aiprovider')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_request_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AITaskConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(choices=[('DRIVE_EXTRACTION', 'Drive Extraction'), ('DRIVE_SUMMARY', 'Drive Summary'), ('STUDENT_CHAT', 'Student Chat'), ('ELIGIBILITY_ANALYSIS', 'Eligibility Analysis'), ('RESUME_ANALYSIS', 'Resume Analysis'), ('WEB_RESEARCH', 'Web Research'), ('GENERAL', 'General Placement AI')], max_length=30, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fallback_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='placements.aiprovider')),
                ('fallback_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='placements.aiprovider')),
                ('fallback_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='placements.aiprovider')),
                ('primary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='placements.aiprovider')),
            ],
            options={
                'ordering': ['task'],
            },
        ),
    ]
