# Generated by Django 5.2.17 on 2026-08-09 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0005_aiprovider_aisettings_aiproviderhealth_aiproviderkey_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='drive',
            name='job_type',
            field=models.CharField(blank=True, choices=[('JOB', 'Job'), ('INTERNSHIP', 'Internship')], default='', help_text='Job or Internship (blank = not specified)', max_length=20),
        ),
        migrations.CreateModel(
            name='DriveChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Student'), ('assistant', 'Placement AI')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='placements.drive')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['drive', 'user'], name='placements__drive_i_77a52e_idx')],
            },
        ),
    ]
