# Generated by Django 5.2.17 on 2026-08-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0006_drive_job_type_drivechatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aitaskconfiguration',
            name='task',
            field=models.CharField(choices=[('DRIVE_EXTRACTION', 'Drive Extraction'), ('DRIVE_SUMMARY', 'Drive Summary'), ('STUDENT_CHAT', 'Student Chat'), ('ELIGIBILITY_ANALYSIS', 'Eligibility Analysis'), ('RESUME_ANALYSIS', 'Resume Analysis'), ('RESUME_OCR', 'Resume OCR'), ('WEB_RESEARCH', 'Web Research'), ('GENERAL', 'General Placement AI')], max_length=30, unique=True),
        ),
    ]
