# Generated by Django 5.2.17 on 2026-08-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0007_alter_aitaskconfiguration_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aitaskconfiguration',
            name='task',
            field=models.CharField(choices=[('DRIVE_EXTRACTION', 'Drive Extraction'), ('DRIVE_SUMMARY', 'Drive Summary'), ('STUDENT_CHAT', 'Student Chat'), ('ELIGIBILITY_ANALYSIS', 'Eligibility Analysis'), ('RESUME_ANALYSIS', 'Resume Analysis'), ('RESUME_OCR', 'Resume OCR'), ('DOCUMENT_OCR', 'Document OCR'), ('WEB_RESEARCH', 'Web Research'), ('GENERAL', 'General Placement AI')], max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='aiusagelog',
            name='action',
            field=models.CharField(choices=[('AI_EXTRACT', 'AI Extract'), ('AI_CHAT', 'AI Chat'), ('AI_ASK', 'AI Ask'), ('AI_RESUME', 'AI Resume Review'), ('AI_DOC_OCR', 'Document OCR')], max_length=20),
        ),
    ]
