# Generated by Django 5.2.17 on 2026-08-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0008_alter_aitaskconfiguration_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiprovider',
            name='provider_type',
            field=models.CharField(choices=[('OPENAI_COMPATIBLE', 'OpenAI Compatible (any)'), ('GEMINI', 'Google Gemini'), ('NVIDIA', 'NVIDIA'), ('RAG', 'NVIDIA RAG NIM'), ('GROQ', 'Groq'), ('CEREBRAS', 'Cerebras'), ('OPENROUTER', 'OpenRouter'), ('MISTRAL', 'Mistral'), ('DEEPSEEK', 'DeepSeek'), ('TOGETHER', 'Together AI')], default='OPENAI_COMPATIBLE', max_length=20),
        ),
    ]
