# Generated by Django 5.2.17 on 2026-08-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0009_alter_aiprovider_provider_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiprovider',
            name='purpose',
            field=models.CharField(choices=[('GENERAL', 'General / All tasks'), ('DRIVE_EXTRACTION', 'Drive Extraction'), ('CHAT', 'Student Chat'), ('RESUME', 'Resume Analysis'), ('RAG', 'RAG / Document Grounding'), ('WEB', 'Web Research')], default='GENERAL', max_length=20),
        ),
    ]
