# Generated by Django 5.2.17 on 2026-08-05 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PROMOTE', 'Promote to CR'), ('DEMOTE', 'Demote to Student'), ('ACTIVATE', 'Activate'), ('DEACTIVATE', 'Deactivate'), ('PASSWORD_RESET', 'Password Reset'), ('CSV_IMPORT', 'CSV Import'), ('CSV_EXPORT', 'CSV Export'), ('DOCUMENT_UPLOAD', 'Document Upload'), ('DOCUMENT_DELETE', 'Document Delete'), ('DOCUMENT_DOWNLOAD', 'Document Download')], max_length=30)),
                ('target_type', models.CharField(blank=True, default='', max_length=60)),
                ('target_id', models.CharField(blank=True, default='', max_length=60)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Audit logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
