# Generated by Django 5.2.17 on 2026-08-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PROMOTE', 'Promote to CR'), ('DEMOTE', 'Demote to Student'), ('ACTIVATE', 'Activate'), ('DEACTIVATE', 'Deactivate'), ('PASSWORD_RESET', 'Password Reset'), ('CSV_IMPORT', 'CSV Import'), ('CSV_EXPORT', 'CSV Export'), ('DOCUMENT_UPLOAD', 'Document Upload'), ('DOCUMENT_DELETE', 'Document Delete'), ('DOCUMENT_DOWNLOAD', 'Document Download'), ('DOCUMENT_SHARE', 'Document Shared'), ('DOCUMENT_FORK', 'Document Forked')], max_length=30),
        ),
    ]
