# Generated by Django 5.2.17 on 2026-08-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_notification_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('DOCUMENT_UPLOAD', 'Document Upload'), ('RESUME_UPLOAD', 'Resume Upload'), ('CONTACT_ADMIN', 'Contact Admin'), ('ANNOUNCEMENT', 'Announcement'), ('DRIVE', 'Placement Drive')], max_length=30),
        ),
    ]
