# Generated by Django 5.2.17 on 2026-08-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_notification_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('DOCUMENT_UPLOAD', 'Document Upload'), ('RESUME_UPLOAD', 'Resume Upload'), ('CONTACT_ADMIN', 'Contact Admin'), ('ANNOUNCEMENT', 'Announcement'), ('DRIVE', 'Placement Drive'), ('AI_RESUME', 'AI Resume Review'), ('AI_REPORT', 'AI Health Report')], max_length=30),
        ),
    ]
