# Generated by Django 5.2.17 on 2026-08-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_notification_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='document_public_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
