# Generated by Django 5.2.17 on 2026-08-16 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_notification_document_public_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('DOCUMENT_UPLOAD', 'Document Upload'), ('RESUME_UPLOAD', 'Resume Upload'), ('CONTACT_ADMIN', 'Contact Admin'), ('ANNOUNCEMENT', 'Announcement'), ('DRIVE', 'Placement Drive'), ('AI_RESUME', 'AI Resume Review'), ('AI_REPORT', 'AI Health Report'), ('FEEDBACK', 'Feedback')], max_length=30),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('IDEA', 'Idea'), ('FEEDBACK', 'Feedback')], db_index=True, default='IDEA', max_length=10)),
                ('title', models.CharField(blank=True, default='', max_length=150)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('NEW', 'New'), ('APPROVED', 'Approved'), ('IMPLEMENTED', 'Implemented'), ('DECLINED', 'Declined')], db_index=True, default='NEW', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
