# Generated by Django 5.2.17 on 2026-08-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('CR', 'CR (Sub Admin)'), ('FACULTY', 'Faculty'), ('STUDENT', 'Student')], default='STUDENT', max_length=20),
        ),
    ]
