# Generated by Django 5.2.17 on 2026-08-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_resume_file_checked_at_resume_is_missing'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
