# Generated by Django 5.2.17 on 2026-08-09 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_passout_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='ats_viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='faculty_access',
            field=models.CharField(blank=True, choices=[('RESUME', 'Resume Portal'), ('PLACEMENT', 'Placement Portal'), ('BOTH', 'Both')], default='BOTH', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='', help_text='Optional - collected during student import or profile edits.', max_length=10),
        ),
        migrations.CreateModel(
            name='AiAccessConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_ai_requests', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('unlimited_ai', models.BooleanField(default=False)),
                ('ats_view_interval_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('daily_resume_uploads', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_access', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_access_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['student__roll_number'],
            },
        ),
    ]
