# Generated by Django 5.2.17 on 2026-08-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_resume_ats_viewed_at_user_avatar_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passout_year',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, help_text='Batch pass-out year (e.g. 2025) - shown next to every student.', null=True),
        ),
    ]
