# Generated by Django 5.2.17 on 2026-08-14 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_search_trigram_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, default='', max_length=80, unique=True)),
                ('is_published', models.BooleanField(default=False)),
                ('headline', models.CharField(blank=True, default='', max_length=200)),
                ('about', models.TextField(blank=True, default='')),
                ('skills', models.JSONField(blank=True, default=list)),
                ('education', models.TextField(blank=True, default='')),
                ('experience', models.TextField(blank=True, default='')),
                ('projects', models.TextField(blank=True, default='')),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('cloudinary_url', models.URLField(blank=True, default='', max_length=500)),
                ('public_id', models.CharField(blank=True, default='', max_length=255)),
                ('is_missing', models.BooleanField(default=False)),
                ('ai_status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('ai_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ai_analysis', models.JSONField(blank=True, null=True)),
                ('ai_error', models.CharField(blank=True, default='', max_length=500)),
                ('ai_analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('rebuilt_sections', models.JSONField(blank=True, null=True)),
                ('rebuilt_text', models.TextField(blank=True, default='')),
                ('rebuilt_file_name', models.CharField(blank=True, default='', max_length=255)),
                ('rebuilt_docx_url', models.URLField(blank=True, default='', max_length=500)),
                ('rebuilt_docx_public_id', models.CharField(blank=True, default='', max_length=255)),
                ('rebuilt_at', models.DateTimeField(blank=True, null=True)),
                ('rebuilt_ai_status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('rebuilt_ai_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rebuilt_ai_analysis', models.JSONField(blank=True, null=True)),
                ('rebuilt_ai_error', models.CharField(blank=True, default='', max_length=500)),
                ('rebuilt_ai_analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
