# Generated by Django 5.2.17 on 2026-08-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='show_contact',
            field=models.BooleanField(default=False),
        ),
    ]
