# Generated by Django 5.2.17 on 2026-08-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_portfolio_show_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='custom_sections',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
