# Generated by Django 5.2.17 on 2026-08-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_portfolio_custom_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='portfolio_enabled',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
