# Generated by Django 5.2.17 on 2026-08-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_portfolio_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='theme',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
