# Generated by Django 5.2.17 on 2026-08-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_portfolio_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='background_image',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='rebuilt_pdf_public_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='rebuilt_pdf_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='rebuilt_tex',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='resume_source',
            field=models.TextField(blank=True, default=''),
        ),
    ]
