# Generated by Django 5.2.17 on 2026-08-14 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_portfolio_background_image_portfolio_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='about',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='custom_sections',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='education',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='headline',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='images',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='show_contact',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='user',
            name='portfolio_enabled',
        ),
    ]
