# Generated by Django 5.2.17 on 2026-08-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_portfolio_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='rebuild_requirements',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='source_ai_analysis',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='source_ai_analyzed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='source_ai_error',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='source_ai_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='source_ai_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='PENDING', max_length=10),
        ),
    ]
