# Generated by Django 5.2.17 on 2026-08-19 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_portfolio_rebuild_requirements_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('target_ats_score', models.PositiveSmallIntegerField(default=80, help_text='Target ATS score (0-100)')),
                ('requirements', models.TextField(blank=True, default='', help_text='Job description or requirements the resume should target')),
                ('template_latex', models.TextField(blank=True, default='', help_text='Sample LaTeX template the AI should follow')),
                ('generated_status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('generated_latex', models.TextField(blank=True, default='')),
                ('generated_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('generated_analysis', models.JSONField(blank=True, null=True)),
                ('generated_error', models.CharField(blank=True, default='', max_length=500)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('compiled_pdf_url', models.URLField(blank=True, default='', max_length=500)),
                ('compiled_pdf_public_id', models.CharField(blank=True, default='', max_length=255)),
                ('compiled_at', models.DateTimeField(blank=True, null=True)),
                ('submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_url', models.URLField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enabled_workspaces', to=settings.AUTH_USER_MODEL)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workspace', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['student__roll_number'],
            },
        ),
    ]
