# Generated by Django 5.2.17 on 2026-08-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_add_studentworkspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentworkspace',
            name='compile_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentworkspace',
            name='generate_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentworkspace',
            name='last_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentworkspace',
            name='submit_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
