# Generated by Django 5.2.17 on 2026-08-05 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('college', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('cloudinary_url', models.URLField(max_length=500)),
                ('public_id', models.CharField(max_length=255, unique=True)),
                ('downloads', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='college.branch')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='college.category')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='college.section')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='college.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='college.subject')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['branch', 'section'], name='documents_d_branch__066b91_idx'), models.Index(fields=['semester', 'category'], name='documents_d_semeste_d72d55_idx'), models.Index(fields=['subject'], name='documents_d_subject_2e1680_idx')],
            },
        ),
    ]
