# Generated by Django 5.2.17 on 2026-08-05 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='forked_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forks', to='documents.document'),
        ),
        migrations.AlterField(
            model_name='document',
            name='public_id',
            field=models.CharField(max_length=255),
        ),
    ]
