# Generated by Django 5.2.17 on 2026-08-06 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
        ('documents', '0002_document_forked_from_alter_document_public_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentShareRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='PENDING', max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_requests', to='documents.document')),
                ('from_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_share_requests', to='college.section')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_share_requests', to=settings.AUTH_USER_MODEL)),
                ('to_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_share_requests', to='college.section')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
