# Generated by Django 5.2.17 on 2026-08-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documentsharerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='is_missing',
            field=models.BooleanField(default=False),
        ),
    ]
