# Generated by Django 5.2.17 on 2026-08-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_file_checked_at_document_is_missing'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
