# Generated by Django 5.2.17 on 2026-08-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_restored_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='submission_deadline',
            field=models.DateField(blank=True, help_text='Optional - for assignments, the last date to submit.', null=True),
        ),
    ]
