# Generated by Django 5.2.17 on 2026-08-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_document_submission_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_checked_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='is_missing',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
