# Generated by Django 5.2.17 on 2026-08-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_alter_document_file_checked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ocr_error',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='document',
            name='ocr_status',
            field=models.CharField(choices=[('NONE', 'Not extracted'), ('PENDING', 'Extracting...'), ('COMPLETE', 'Text available'), ('FAILED', 'Extraction failed')], db_index=True, default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='ocr_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='document',
            name='ocr_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
